### PR TITLE
Update for Gleam v0.32

### PR DESCRIPTION
**Pull request by lpil**
I've also made the tmp files be written to a git ignored `tmp` rather than into the src tree as a crash half way through the tests left me with various test files to delete before I could run the tests again. I hope that's ok!

### CODE REVIEW

**Comment by bcpeinhardt** [comment]
You're positively fabulous for taking the time to do this, sorry I've been consumed with the new job. I plan to rejoin the gleam asap 😃

**Comment by bcpeinhardt** [comment]
Because of the way main (in test) is set up, the tests will sometimes fail to run (because `delete("/tmp")` will return an `Error` if there's no /tmp to begin with). Would you mind changing that line to ignore the delete result and then assert tmp does not exist, or use `delete_all` which will ignore an `Enoent` error?

**Comment by lpil** [comment]
Oh yes! Thank you

**Comment by bcpeinhardt** [comment]
Published as 0.2.0 (just felt right with the whole new gleam version)

**Pull request merged**
